cloud:
  aws:
    stack:
      auto: false

templates:
  - event: CREATED
    subject: "Welcome to EPAM Training"
    from: danyil_shykh@epam.com
    template: welcome-template.html

  - event: DELETED
    subject: "We will miss you!"
    from: danyil_shykh@epam.com
    template: bye-bye-template.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always